version: '3.8'

services:
  mysql-academia:
    image: mysql:8
    container_name: academia
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: academia
    ports:
      - "3300:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  mysql_data: